name: 中青阅读

on:
  schedule:
    - cron: '10,40 23,0,1,2,3,4,5,6,7,8,9,10,16,17,18,19,20,21,22 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 中青阅读' 
        run: python3 youth_read.py 
        env:
            YOUTH1_READ_BODY1: ${{ secrets.YOUTH1_READ_BODY1}}  #必须
            # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非私密信息，去掉
    
